---
name: Go build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install protoc
        run: |
          sudo apt-get update && sudo apt-get install gcc-multilib nodejs npm curl unzip -y
          mkdir -p $HOME/protobuf && pushd $HOME/protobuf
          curl -o protoc.zip -L 'https://github.com/protocolbuffers/protobuf/releases/download/v27.0/protoc-27.0-linux-x86_64.zip'
          unzip protoc.zip
          popd
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y gcc gcc-mingw-w64
          export PATH=$HOME/.local/bin:$HOME/protobuf/bin:$PATH
          make dev-dependencies
          make
