---
name: Go release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install gcc-multilib curl unzip gcc-mingw-w64 -y
          mkdir -p $HOME/protobuf && pushd $HOME/protobuf
          curl -o protoc.zip -L 'https://github.com/protocolbuffers/protobuf/releases/download/v27.0/protoc-27.0-linux-x86_64.zip'
          unzip protoc.zip
          popd
          mkdir -p $HOME/upx && pushd $HOME/upx
          curl -o upx.tar.xz -L 'https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz'
          tar xJf upx.tar.xz
          cp upx-*/upx .
          popd
      - name: Build
        run: |
          export PATH=$HOME/.local/bin:$HOME/protobuf/bin:$HOME/upx:$PATH
          make dev-dependencies
          make
          chmod +x pkcs11-proxy* && find . -maxdepth 1 -type f -name "pkcs11-proxy-*" -exec sh -c 'upx --best -o s$(basename {}) {}' \;
      - uses: softprops/action-gh-release@v2
        with:
          files: "*pkcs11-proxy-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
